[programs.localnet]
confidential_bench = "ConfBenchProg11111111111111111111111111111"

[registry]
url = "https://api.arcium.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "ConfBenchProg11111111111111111111111111111"
program = "./target/deploy/confidential_bench.so"